#!/usr/bin/env bash
# issue-body.sh — GitHub issue body format helper
#
# Round 2 I6: blank line between body text and `---` separator (markdown HR rendering).
# Footer (source/fingerprint) is generated by skill side, never by LLM (anti-injection).

format_body() {
  local owner_tag="$1"
  local body_text="$2"
  local skill="$3"
  local source_id="$4"
  local fingerprint="$5"

  if [[ -z "$skill" || -z "$source_id" || -z "$fingerprint" ]]; then
    echo "format_body: skill / source_id / fingerprint required" >&2
    return 1
  fi

  if [[ -n "$owner_tag" ]]; then
    printf '%s\n\n' "$owner_tag"
  fi
  printf '%s\n\n' "$body_text"
  printf -- '---\n'
  printf 'source: %s:%s\n' "$skill" "$source_id"
  printf 'fingerprint: %s\n' "$fingerprint"
}

extract_owner_tag() {
  local body="$1"
  local first_line
  first_line="$(printf '%s' "$body" | head -n 1)"
  case "$first_line" in
    '[CC]'|'[CX]'|'[?]'|'[USER]') printf '%s' "$first_line" ;;
    *) printf '' ;;
  esac
}
