#!/usr/bin/env bash
# issue-dedup.sh — claim / finalize / release HTTP client for receiver
#
# Round 3 W1: claim_id is generated by skill side (UUIDv4) for HTTP retry idempotency.
# All endpoints are idempotent on the receiver side.

# shellcheck disable=SC1091
SCRIPT_DIR_DEDUP="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR_DEDUP/secrets.sh"

_dedup_sign() {
  local payload="$1"
  local secret="$2"
  printf '%s' "$payload" | openssl dgst -sha256 -hmac "$secret" -hex | awk '{print $NF}'
}

_dedup_post() {
  local path="$1"
  local body_json="$2"
  local base_url="${RECEIVER_BASE_URL:-}"
  if [[ -z "$base_url" ]]; then
    echo "dedup: RECEIVER_BASE_URL not set" >&2
    return 4
  fi
  local secret
  secret="$(secret_get webhook_receiver_shared_secret)" || return 4
  local sig
  sig="$(_dedup_sign "$body_json" "$secret")"
  local resp http_code
  resp="$(curl -fsS -m 30 -X POST \
            -H 'content-type: application/json' \
            -H "X-Mijica-Signature: $sig" \
            -w "\n__HTTP_CODE__%{http_code}" \
            -d "$body_json" \
            "${base_url}${path}" 2>/dev/null)" || {
    echo "dedup: network error on $path" >&2
    return 4
  }
  http_code="${resp##*__HTTP_CODE__}"
  resp="${resp%__HTTP_CODE__*}"
  printf '%s' "$resp"
  case "$http_code" in
    2*) return 0 ;;
    409|410) return 2 ;;
    4*)  return 2 ;;
    5*)  return 3 ;;
    *)   return 4 ;;
  esac
}

# dedup_claim <skill> <fingerprint> <repo> <payload_json> <claim_id> [severity] [bypass_backpressure]
# stdout: JSON {should_create, claim_id, reason?, existing_issue_number?}
dedup_claim() {
  local skill="$1" fp="$2" repo="$3" payload="$4" claim_id="$5"
  local severity="${6:-info}" bypass="${7:-false}"
  local body
  body="$(jq -nc \
            --arg skill "$skill" \
            --arg fp "$fp" \
            --arg repo "$repo" \
            --argjson payload "$payload" \
            --arg claim_id "$claim_id" \
            --arg severity "$severity" \
            --argjson bypass "$bypass" \
            '{skill:$skill, fingerprint:$fp, repo:$repo,
              issue_payload:$payload, claim_id:$claim_id,
              severity:$severity, bypass_backpressure:$bypass}')"
  _dedup_post "/api/dedup/claim" "$body"
}

# dedup_finalize <claim_id> <issue_number>
dedup_finalize() {
  local claim_id="$1" issue_number="$2"
  local body
  body="$(jq -nc --arg cid "$claim_id" --argjson n "$issue_number" \
            '{claim_id:$cid, issue_number:$n}')"
  _dedup_post "/api/dedup/finalize" "$body"
}

# dedup_release <claim_id> <reason>
dedup_release() {
  local claim_id="$1" reason="$2"
  local body
  body="$(jq -nc --arg cid "$claim_id" --arg r "$reason" \
            '{claim_id:$cid, reason:$r}')"
  _dedup_post "/api/dedup/release" "$body"
}
